export const lectures = [
  { name: "Histerossalpingografia e histerossonosalpingografia (HyCosy)", isFixed: false },
  { name: "HisteroRM", isFixed: false },
  { name: "Anomalias mullerianas: nova classificação", isFixed: false },
  { name: "A visão do fertileuta: o que não pode faltar no laudo", isFixed: false },
  { name: "Mesa redonda e discussão", isFixed: false },
  { name: "Abertura", isFixed: false },
  { name: "Protocolos de Ressonancia Magnetica", isFixed: false },
  { name: "Como entender as imagens", isFixed: false },
  { name: "Anatomia da pelve - Compartimentos anterior", isFixed: false },
  { name: "Anatomia da pelve - Compartimentos médio e posterior", isFixed: false },
  { name: "Doenças pélvicas extra ginecológicas", isFixed: false },
  { name: "Câncer de ovário: clínica e achados clássicos", isFixed: false },
  { name: "DTG: clínica e achados clássicos", isFixed: false },
  { name: "Endometriose: clínica e achados clássicos", isFixed: false },
  { name: "Câncer de colo uterino: clínica e achados clássicos", isFixed: false },
  { name: "Câncer de endométrio: clínica e achados clássicos", isFixed: false },
  { name: "Acidente Vascular Cerebral: Do Diagnóstico à Terapia Endovascular", isFixed: false },
  { name: "Padrões clássicos e armadilhas diagnósticas na TC e RM no Trauma Cranioencefálico", isFixed: false },
  { name: "O papel da neuroimagem na decisão entre manejo conservador e cirúrgico nas hemorragias intracranianas", isFixed: false },
  { name: "Lesões Vasculares Associadas ao Trauma: O Que Não Pode Passar Despercebido?", isFixed: false },
  { name: "Sessão Interativa de Casos", isFixed: false },
  { name: "Atrofia Cerebral na Doença de Alzheimer: Escalas visuais e volumetria automatizada na prática clínica", isFixed: false },
  { name: "Biomarcadores de Imagem na Demência Frontotemporal e Outras Demências Atípicas", isFixed: false },
  { name: "O Papel do PET no Diagnóstico Precoce de Demências", isFixed: false },
  { name: "Doença de Parkinson e Síndromes Parkinsonianas: Como Diferenciar por Imagem?", isFixed: false },
  { name: "Sessão interativa de casos", isFixed: false },
  { name: "Respondendo 10 mitos sobre a mamografia", isFixed: false },
  { name: "Assimetria e distorção arquitetural na era da tomossíntese", isFixed: false },
  { name: "Mama densa em 2025 - qual a melhor forma de não deixar escapar o câncer?", isFixed: false },
  { name: "Desafios em ultrassonografia mamária", isFixed: false },
  { name: "Discussão", isFixed: false },
  { name: "Discussão de caso clínico: Ca em jovem tumor board", isFixed: false },
  { name: "Discussão de caso clínico: Calcificações pós-QT neoadjvuvante", isFixed: false },
  { name: "Discussão de caso clínico: Lesão BI-RADS 3 em exame de estadiamento", isFixed: false },
  { name: "Discussão: idosa com tumor luminal: papel do US e da biópsia de linfonodo sentinela", isFixed: false },
  { name: "Bases da imunologia do carcinoma de mama", isFixed: false },
  { name: "Estadiamento do câncer de mama pelos métodos de imagem", isFixed: false },
  { name: "A mama e a tomografia", isFixed: false },
  { name: "Lesões cutâneas na mama", isFixed: false },
  { name: "O descalonamento de QT: o que o oncologista espera da imagem", isFixed: false },
  { name: "Onde estamos na avaliação inicial e pós QT neodjuvante da axila? INSEMA, SOUND e ALLIANCE", isFixed: false },
  { name: "Imuno-histoquímica: entendendo além do habitual", isFixed: false },
  { name: "Sessão anatomorradiológica", isFixed: false },
  { name: "Lesão do Lábio Glenoidal", isFixed: false },
  { name: "Instabilidade carpal", isFixed: false },
  { name: "Miopatia Inflamatória", isFixed: false },
  { name: "Avaliação das articulações sacro-ilíacas no contexto reumatológico", isFixed: false },
  { name: "Lesões musculares na panturrilha", isFixed: false },
  { name: "Lesão osteocondral no tornozelo ou sarcoma (TEMA A CONFIRMAR)", isFixed: false },
  { name: "Tornozelo (TEMA A CONFIRMAR)", isFixed: false },
  { name: "Pubalgia no atleta", isFixed: false },
  { name: "Lesão meniscal tipo Rampa", isFixed: false },
  { name: "Mieloma múltiplo (TEMA A CONFIRMAR)", isFixed: false },
  { name: "Lesões traumáticas do pé", isFixed: false },
  { name: "Tumor partes moles ou infecção (TEMA A CONFIRMAR)", isFixed: false },
  { name: "Pós-operatório do ombro", isFixed: false },
  { name: "pé e tnz", isFixed: false },
  { name: "Mão", isFixed: false },
  { name: "O papel do radiologista no rastreamento do câncer de próstata: devemos expandir o uso da ressonância magnética biparamétrica?", isFixed: false },
  { name: "Podemos evitar a biópsia no manejo de pacientes com câncer de próstata em vigilância ativa?", isFixed: false },
  { name: "Teranóstica no câncer de próstata: imagens e terapias integradas na era da oncologia de precisão", isFixed: false },
  { name: "VI-RADS na avaliação do câncer de bexiga: indicações, limitações e pitfalls", isFixed: false },
  { name: "Caso clínico - discussão multidisciplinar", isFixed: false },
  { name: "Joelho", isFixed: false },
  { name: "Espondiloartrite", isFixed: false },
  { name: "Ultrassonografia na avaliação de patologias inflamatórias e tumorais do escroto e papel da RM nos casos inconclusivos ao estudo ultrassonográfico", isFixed: false },
  { name: "Investigação de infertilidade masculina- o que o urologista espera do laudo de uma ressonância magnética da pelve", isFixed: false },
  { name: "Achados radiológicos nos casos de hematoespermia e obstrução do trato seminal", isFixed: false },
  { name: "Ressonância Magnética do Pênis: Anatomia, Patologias e Achados Essenciais", isFixed: false },
  { name: "Ca de reto: achados de imagem definidores de tratamento", isFixed: false },
  { name: "Ca de colon: achados de imagem definidores de tratamento", isFixed: false },
  { name: "Visao do coloprocto", isFixed: false },
  { name: "Visao do oncologista", isFixed: false },
  { name: "DISCUSSÃO MULTIDISCIPLINAR", isFixed: false },
  { name: "LI-RADS, atualizacao", isFixed: false },
  { name: "Como avaliar doencas hepaticas difusas (esteatose, ferro...)", isFixed: false },
  { name: "Avaliacao pre-cirurgica de lesoes hepaticas e pre-TX: o que relatar?", isFixed: false },
  { name: "Abordagens minimamente invasivas de lesoes hepaticas focais", isFixed: false },
  { name: "Rastreamento do adenocarcinoma de pancreas", isFixed: false },
  { name: "Lesoes cisticas pancreaticas- aspectos de imagem", isFixed: false },
  { name: "Seguimento clinico de lesoes cisticas pancreaticas", isFixed: false },
  { name: "Abordagem endoscopica de lesoes pancreaticas", isFixed: false },
  { name: "Ca de vias biliares", isFixed: false },
  { name: "Ca de vesicula biliar", isFixed: false },
  { name: "Tratamento locorregional adenocarcinoma via biliar", isFixed: false },
  { name: "Visão oncologista", isFixed: false },
  { name: "Física do Raio-X e Tomografia", isFixed: false },
  { name: "Interpretação do Raio - X de tórax", isFixed: false },
  { name: "Anatomia radiológica torácica", isFixed: false },
  { name: "Anatomia radiológica abdominal", isFixed: false },
  { name: "Discussão de casos", isFixed: false },
  { name: "Emergências traumáticas SNC", isFixed: false },
  { name: "Emergências não-traumáticas SNC", isFixed: false },
  { name: "Emergências torácicas", isFixed: false },
  { name: "Emergências abdominais", isFixed: false },
  { name: "Métodos de imagem em oncologia", isFixed: false },
  { name: "Screening - indicações na imagem", isFixed: false },
  { name: "Radiologia cardiovascular - técnicas de imagem", isFixed: false },
  { name: "Emergências cardiovasculares", isFixed: false },
  { name: "Inteligência artifical e inovação na radiologia", isFixed: false },
  { name: "Radiologia intervencionista: aplicações e perspectivas futuras", isFixed: false },
  { name: "A carreira da radiologia", isFixed: false },
  { name: "Hands-on", isFixed: false },
  { name: "Atualização do glossário de termos em imagem torácica da Sociedade Fleischner 2024", isFixed: false },
  { name: "Anormalidades Intersticiais Pulmonares - ILA: como eu laudo", isFixed: false },
  { name: "Imagem na Hipertensão Pulmonar: como eu faço e laudo o exame", isFixed: false },
  { name: "Dor torácica no Pronto Atendimento: o que procurar", isFixed: false },
  { name: "Doenças infecciosas pulmonares raras e desafiadoras: quando suspeitar", isFixed: false },
  { name: "TNM 9a edição - atualizações no estadiamento da neoplasia pulmonar", isFixed: false },
  { name: "Estadiamento da neoplasia pulmonar - como eu laudo", isFixed: false },
  { name: "Avaliação pós-tratamento da neoplasia pulmonar - como eu laudo", isFixed: false },
  { name: "Planejamento tridimensional de ressecções pulmonares", isFixed: false },
  { name: "Board Multidisciplinar: Casos clínicos desafiadores", isFixed: false },
  { name: "Introdução; Conceitos Básicos: Big Data, AI, Machine Learning", isFixed: false },
  { name: "Features, modelos, performances", isFixed: false },
  { name: "Regressão Linear, Gradient Descent e regressão logística", isFixed: false },
  { name: "Prática: Regressão Linear, Gradient Descent e regressão logística", isFixed: false },
  { name: "Naive Bayes, árvores de decisão e SVM", isFixed: false },
  { name: "Estatística / métricas", isFixed: false },
  { name: "Pré-processamento", isFixed: false },
  { name: "Prática: overfitting/underfitting", isFixed: false },
  { name: "Redes neurais artificiais", isFixed: false },
  { name: "Deep learning", isFixed: false },
  { name: "Prática: Redes neurais convolucionais (CNN)", isFixed: false },
  { name: "Aplicações na Radiologia", isFixed: false },
  { name: "Modelos de linguagem: redes neurais recorrentes e transformers", isFixed: false },
  { name: "Prática: ChatGPT e outros LLMs", isFixed: false },
  { name: "IA e o futuro da Radiologia", isFixed: false }
];

export const categories = [
  { name: "Palestrante", isFixed: true },
  { name: "Debatedor", isFixed: false },
  { name: "Moderador", isFixed: false }
]

export const speakers = [
  {
    full_name: "Fernando Morbeck Almeida Coelho",
    badge_name: "Fernando Morbeck Coelho",
    email: "dr.fernandomorbeck@gmail.com",
    phone: "(11)942341117",
    cpf: "02017839590",
    city: "São Paulo",
    state: "SP",
    curriculum: "Coordenador do Grupo de Geniturinário do Instituto de Radiologia da FMUSP; Radiologista Abdominal do Hospital Albert Einstein; Segundo Secretário e membro da comissão científica do CBR; Doutor em Ciências da Saúde pelo Albert Einstein.",
    categories: [{ id: 1 }],
    lectures: [{ id: 52 },{ id: 55 },{ id: 58 }],
    photo_path: "https://res.cloudinary.com/dixe3b2i5/image/upload/v1740492798/speakers/02017839590.jpg",
    year: 2025,
    created_at: "2025-02-26 03:57:31.841",
    updated_at: "2025-02-26 03:57:31.841"
  }
]